name: Test macOS and linux platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-apple:
    name: Test (macOS)
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # macOS only
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
            
      - name: Test macOS
        run: |
          xcodebuild test \
            -scheme fs-get-app-status \
            -destination "platform=macOS" \
            -enableCodeCoverage YES \
            -skipPackagePluginValidation

      - name: Fetch Coverage
        uses: sersoft-gmbh/swift-coverage-action@v4
        id: coverage-files

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ${{ join(fromJSON(steps.coverage-files.outputs.files), ',') }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest
    container: swift:6.0-jammy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: swift build -v

      - name: Test with coverage
        run: swift test --enable-code-coverage -v --parallel

      - name: Generate coverage
        run: |
          PROF_DIR=$(find .build -type d -name codecov | head -n 1)
          echo "Profdata dir: $PROF_DIR"

          llvm-profdata merge -sparse $PROF_DIR/*.profdata -o coverage.profdata

          XCTEST=$(find .build -name "*.xctest" | head -n 1)

          llvm-cov export \
            -instr-profile=coverage.profdata \
            "$XCTEST" \
            > coverage.json

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
